# rustfmt.toml - Project formatting rules

max_width = 120
edition = "2021"
use_small_heuristics = "Max"
tab_spaces = 4
hard_tabs = false
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
reorder_imports = true